// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ildaiqtamtawjuoveuuq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlsZGFpcXRhbXRhd2p1b3ZldXVxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjY0MDU3MDEsImV4cCI6MjA4MTk4MTcwMX0.R4_JT8-ZYJP3HWo2pnwWJ2Ip_Ns4iRjk1E6fw9b3PO8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
});
